language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS=

matrix:
  fast_finish: true
  include:
    - php: 7.2
      dist: bionic
      env: deps=low
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: nightly
      dist: bionic
      env: COMPOSER_ARGS=--ignore-platform-reqs

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update --snapshot
  - git clone https://github.com/jrfnl/PHP-Parallel-Lint parallel-lint
  - cd parallel-lint
  - git checkout feature/33-ignore-startup-errors
  - cd ../
  - if [ "$deps" == "low" ]; then composer update -n --prefer-dist --prefer-lowest --prefer-stable $COMPOSER_ARGS; fi
  - if [ "$deps" != "low" ]; then composer update -n --prefer-dist $COMPOSER_ARGS; fi

script:
  - composer lint
  - composer test
