language: php

sudo: false
dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 7.2
          env: deps=low
    fast_finish: true
    allow_failures:
      - php: nightly

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [ "$deps" == "low" ]; then composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-dist; fi

script: composer test
